### ISSUE TITLE
El workflow de GitHub de VeTube x64 no encuentra ESpeak Phonemizer porque falta la variable VERSION

### ISSUE THREAD

**Issue by ogomez92** [metalalchemist/VeTube#17]
Puedes mirarte esto porfa?

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ogome\\Downloads\\VeTube-x64\\_internal\\espeak_phonemizer\\VERSION'

No sé si hay que hacer algo más aparte de meter la variable esta.

**Comment by rmcpantoja** [comment]
Hola @ogomez92,
__version__ está creado en el repositorio del paquete. ¿Lo instalaste a través de requirements.txt? De todos modos, puedes intentar con:
```
pip install git+https://github.com/mush42/espeak-phonemizer-windows
```
Según mis pruebas en esta parte, GitHub Actions es capaz de crear el artefacto correctamente.

**Comment by rmcpantoja** [comment]
Actualización: mi error, se debe a la actualización más reciente de pyinstaller. Ahora debería crear la compilación correctamente.
